Support running 'import' and 'state' (with arguments)

diff --git a/terraformsh b/terraformsh
--- a/terraformsh
+++ b/terraformsh
@@ -62,6 +62,7 @@ _usage () {
     INIT_ARGS=(${INIT_ARGS[@]})
     IMPORT_ARGS=(${IMPORT_ARGS[@]})
     GET_ARGS=(${GET_ARGS[@]})
+    STATE_ARGS=(${STATE_ARGS[@]})
 
   To use the 'aws_bootstrap' command, pass the '-b FILE' option and make sure the
   file(s) have the following variables:
@@ -89,15 +90,15 @@ _usage () {
       plan
     \`\`\`
  - Run plan on a module, passing any configs in specific directories:
-   ```
-   $0 \
-      -C ../../modules/my-database/ \
-      *.tfvars \
-      *.backend.tfvars \
-      my-database/*.tfvars \
-      my-database/*.backend.tfvars \
-      plan
-   ```
+    \`\`\`
+    $0 \
+       -C ../../modules/my-database/ \
+       *.tfvars \
+       *.backend.tfvars \
+       my-database/*.tfvars \
+       my-database/*.backend.tfvars \
+       plan
+    \`\`\`
 
 # Options
     -f FILE           A file passed to Terraform's -var-file option
@@ -123,9 +124,12 @@ _usage () {
     approve           Prompts the user to approve the next step, or the program will exit with an error.
     aws_bootstrap     Looks for 'bucket' and 'dynamodb_table' in your '-b' file options.
                       If found, creates the bucket and table and initializes your Terraform state with them.
+    import            Run \`terraform import [...]\`
+    state             RUn \`terraform state [...]\`
 EOUSAGE
     exit 1
 }
+declare -a VALID_COMMANDS=("plan" "apply" "plan_destroy" "destroy" "shell" "refresh" "validate" "init" "clean" "clean_modules" "approve" "aws_bootstrap" "import" "state")
 
 # ---------------------------------------------------------------------------------------- #
 # ------------------           functions                       --------------------------- #
@@ -134,45 +138,50 @@ _cmd_plan () {
     _cmd_validate
     ( set -x; $TERRAFORM plan "${VARFILE_ARG[@]}" "${PLAN_ARGS[@]}" )
 }
-
 _cmd_apply () {
     _cmd_init
     ( set -x; $TERRAFORM apply "${APPLY_ARGS[@]}" ) && rm -f "$TF_PLANFILE"
 }
-
 _cmd_plan_destroy () {
     _cmd_validate
     ( set -x; $TERRAFORM plan "${VARFILE_ARG[@]}" -destroy "${PLANDESTROY_ARGS[@]}" )
 }
-
 _cmd_destroy () {
     _cmd_init
     ( set -x; $TERRAFORM apply "${DESTROY_ARGS[@]}"  ) && rm -f "$TF_DESTROY_PLANFILE"
 }
-
 # Validate doesn't require 'init' to check the .tf files syntax, but it does
 # require init once it gets to the providers
 _cmd_validate () {
     _cmd_get
     ( set -x; $TERRAFORM validate "${VARFILE_ARG[@]}" )
 }
-
 _cmd_get () {
     _cmd_init # 'terraform get' does nothing if we have not initialized terraform
     ( set -x; $TERRAFORM get "${GET_ARGS[@]}" )
 }
-
 _cmd_refresh() {
     _cmd_init
     ( set -x; $TERRAFORM refresh "${VARFILE_ARG[@]}" "${REFRESH_ARGS[@]}" )
 }
-
 # Note: this line may need to be modified to pipe 'yes no | ' to the beginning 
 # of the Terraform command, if you notice any problems with init in the future.
 _cmd_init () {
     ( set -x; $TERRAFORM init "${INIT_ARGS[@]}" )
 }
-
+_cmd_import () {
+    ( set -x; $TERRAFORM import "${VARFILE_ARG[@]}" "${IMPORT_ARGS[@]}" "$@" )
+}
+_cmd_state () {
+    # 'terraform state' takes no options, but its commands do, so we play argument musical chairs
+    declare -a _args=() _opts=("$@")
+    _cmd=""
+    if [ ${#_opts[@]} -gt 0 ] ; then
+        _cmd="$1"; shift
+        _args+=("${_opts[@]:1}")
+    fi
+    ( set -x; $TERRAFORM state $_cmd "${STATE_ARGS[@]}" "${_args[@]}" )
+}
 # The following allows you to do something like 'terraformsh plan shell' to drop
 # into a shell in the working directory of the root module to be used, with
 # everything ready to run 'terraform' commands (such as 'terraform state list')
@@ -180,7 +189,6 @@ _cmd_shell () {
     _cmd_get
     bash -i -l
 }
-
 # This is basically in case the directory structure where this runs was changed
 # after an initial terraform run. Terraform sucks at cleaning up broken symlinks
 # and its modules.json, so unless we want to have a *ton* of complex logic here,
@@ -188,12 +196,10 @@ _cmd_shell () {
 _cmd_clean_modules () {
     ( set -x; rm -v -rf .terraform/modules/* )
 }
-
 _cmd_clean () {
     _cmd_clean_modules
     ( set -x; rm -vrf "$TF_PLANFILE" "$TF_DESTROY_PLANFILE" .terraform/terraform.tfstate terraform.tfstate || true )
 }
-
 _cmd_approve () {
     echo ""
     read -p "Are you SURE you want to apply the above plan? Type 'YES' to apply now: " APPROVE
@@ -205,7 +211,6 @@ _cmd_approve () {
     fi
     echo ""
 }
-
 # This function is used to bootstrap a new AWS remote state file.
 # You would typically run this in a brand new region, or for a brand new
 # root module, to create the initial state file. It will attempt to re-use
@@ -229,10 +234,8 @@ _cmd_aws_bootstrap () {
 
     # Set a local terraform backend
     printf "terraform {\n\tbackend local {}\n}\n" > terraform-backend.tf
-
     # First remove any existing previous local state
     _cmd_clean
-
     # Initialize local state
     _cmd_init
 
@@ -272,7 +275,6 @@ _cmd_aws_bootstrap () {
 
     ( set -x ; $TERRAFORM init "${INIT_ARGS[@]}" "${BACKENDVARFILE_ARG[@]}" )
 }
-
 _default_vars () {
     # Help load AWS credentials, and silence some messages for automation.
     AWS_SDK_LOAD_CONFIG="${AWS_SDK_LOAD_CONFIG:-1}"
@@ -293,8 +295,8 @@ _default_vars () {
     INIT_ARGS=("-input=false")
     IMPORT_ARGS=("-input=false")
     GET_ARGS=("-update=true")
+    STATE_ARGS=("-input=false")
 }
-
 _final_vars () {
     if [ $USE_PLANFILE -eq 1 ] ; then
         PLAN_ARGS+=("-out=$TF_PLANFILE")
@@ -305,12 +307,12 @@ _final_vars () {
     if [ ${#BACKENDVARFILE_ARG[@]} -lt 1 ] ; then
         echo "$0: WARNING: No -b option passed! Potentially using only local state."
         echo ""
+        sleep 1
         INIT_ARGS+=("-reconfigure" "-force-copy")
     else
         INIT_ARGS+=("-reconfigure" "-force-copy" "${BACKENDVARFILE_ARG[@]}")
     fi
 }
-
 _load_conf () {
     # Don't load the default configs if one was passed via '-c'
     if [ ${#CONF_FILE[@]} -lt 1 ] ; then
@@ -326,6 +328,40 @@ _load_conf () {
         done
     fi
     return 0
+}
+_process_cmds () {
+    for c in "${CMDS[@]}" ; do
+        # If a config file (*.backend.tfvars, *.backend, *.tfvars, *.tfvars.json) was 
+        # passed without the '-b' or '-f' option, add the correct options to use them
+        if [ $(expr "$c" : ".*\.backend\.tfvars$") -ne 0 -o $(expr "$c" : ".*\.backend$") -ne 0 ] ; then
+            BACKENDVARFILE_ARG+=("-backend-config" "$(readlinkf "$c")")
+        elif [ $(expr "$c" : ".*\.tfvars$") -ne 0 -o $(expr "$c" : ".*\.tfvars\.json$") -ne 0 ] ; then
+            VARFILE_ARG+=("-var-file" "$(readlinkf "$c")")
+        else
+            valid_cmd=0
+            for cmd in "${VALID_COMMANDS[@]}" ; do
+                if [ "$cmd" = "$c" ] ; then
+                  TMPCMDS+=("$c") 
+                  valid_cmd=1
+                  break
+                fi
+            done
+            if [ $valid_cmd -eq 0 ] ; then
+                echo "$0: WARNING: '$c' is not a valid command; passing as an option instead"
+                OPTS+=("$c")
+            fi
+        fi
+    done
+    CMDS=("${TMPCMDS[@]}")
+    if [ ${#CMDS[@]} -lt 1 ] ; then
+        echo "$0: Error: No COMMAND was specified"
+        echo ""
+        _usage
+    fi
+    if [ ${#CMDS[@]} -gt 1 -a ${#OPTS[@]} -gt 0 ] ; then
+        echo "$0: Error: you passed multiple commands with some non-command arguments; you can only pass non-command arguments with a single valid command."
+        exit 1
+    fi
 }
 readlinkf() {
   [ "${1:-}" ] || return 1; m_s=40; CDPATH=''; t=$1; [ -e "${t%/}" ] || t=${1%"${1##*[!/]}"}
@@ -347,7 +383,7 @@ readlinkf() {
 SHOW_HELP=0
 declare -a BACKENDVARFILE_ARG=() VARFILE_ARG=() CMDS=() CD_DIRS=() CONF_FILE=()
 declare -a PLAN_ARGS=() APPLY_ARGS=() PLANDESTROY_ARGS=() DESTROY_ARGS=()
-declare -a REFRESH_ARGS=() INIT_ARGS=() IMPORT_ARGS=() GET_ARGS=()
+declare -a REFRESH_ARGS=() INIT_ARGS=() IMPORT_ARGS=() GET_ARGS=() STATE_ARGS=()
 
 _default_vars
 
@@ -387,33 +423,16 @@ _load_conf
 
 [ ${#CMDS[@]} -eq 0 ] && CMDS=("$@")
 
-# If a config file (*.backend.tfvars, *.backend, *.tfvars, *.tfvars.json) was 
-# passed without the '-b' or '-f' option, add the correct options to use them
-declare -a TMP=()
-for c in "${CMDS[@]}" ; do
-    if [ $(expr "$c" : ".*\.backend\.tfvars$") -ne 0 -o $(expr "$c" : ".*\.backend$") -ne 0 ] ; then
-        BACKENDVARFILE_ARG+=("-backend-config" "$(readlinkf "$c")")
-    elif [ $(expr "$c" : ".*\.tfvars$") -ne 0 -o $(expr "$c" : ".*\.tfvars\.json$") -ne 0 ] ; then
-        VARFILE_ARG+=("-var-file" "$(readlinkf "$c")")
-    else
-        TMP+=("$c")
-    fi
-done
-CMDS=("${TMP[@]}")
+declare -a TMPCMDS=() OPTS=()
+_process_cmds
 
 # Change to directories
 for dir in "${CD_DIRS[@]}" ; do
     cd "$dir"
 done
 
-if [ ${#CMDS[@]} -lt 1 ] ; then
-    echo "$0: Error: No COMMAND was specified"
-    echo ""
-    _usage
-fi
-
 _final_vars
 
 for name in "${CMDS[@]}" ; do
-    _cmd_"$name"
+    _cmd_"$name" "${OPTS[@]}"
 done
